# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cover_Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'replies',
            },
        ),
        migrations.CreateModel(
            name='Cover_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_title', models.CharField(max_length=200)),
                ('request_course', models.CharField(max_length=200)),
                ('request_room', models.CharField(max_length=200)),
                ('request_time', models.CharField(max_length=200)),
                ('request_date', models.CharField(max_length=200)),
                ('request_value', models.CharField(max_length=200)),
                ('request_notes', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cover_reply',
            name='cover_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hours_swap.Cover_Request'),
        ),
        migrations.AddField(
            model_name='cover_reply',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
